const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEMS: "ADD_ITEMS",
  CLEAR_ITEMS_FROM_CART: "CLEAR_ITEMS_FROM_CART",
  REMOVE_ITEMS: "REMOVE_ITEMS",
};

export default cartActionTypes;
